### ISSUE TITLE
Broken in the last Dusk (6.14) release

### ISSUE THREAD

**Issue by inventionate** [stechstudio/laravel-visual-testing#5]
Unfortunately, the latest Dusk release (https://github.com/laravel/dusk/releases/tag/v6.14.0) seems to make this package useless. I hope this can be resolved soon? 

Thanks anyway for the helpful visual testing opportunity!

**Comment by jszobody** [comment]
It looks like it was moving the commands to the `boot` method that broke it:

https://github.com/laravel/dusk/pull/884/files

This package overrides the Dusk commands, so I probably just need to move mine to the boot method as well. I don't have time to test this out right now, happy to accept a PR if you do. Otherwise should be able to get to it in a few weeks.

**Comment by inventionate** [comment]
Thanks for the fast reply. Yes, it does seem to be enough to copy the overwriting commands. Unfortunately, I probably don't have time to test this intensively at the moment as well. If I do get around to it, I'll be happy to send a PR.

**Comment by jszobody** [comment]
Version 2.0 was just tagged. It fixes this issue and only targets Duck 6.* now (hence the major version number). You should be all set.

**Comment by inventionate** [comment]
Thank you very much!
